services:
  - type: web
    name: amiabot
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: OPENAI_API_KEY
        value: REPLACE_WITH_YOUR_ACTUAL_OPENAI_API_KEY
